# Generated by Django 5.2.5 on 2025-09-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('round_robin', 'Todos contra Todos'), ('knockout', 'Eliminatorias'), ('group_stage', 'Fase de Grupos')], default='round_robin', max_length=30),
        ),
        migrations.AddField(
            model_name='tournament',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='max_teams',
            field=models.PositiveIntegerField(default=16),
        ),
        migrations.AddField(
            model_name='tournament',
            name='prize_pool',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='registration_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('cedula', 'team')},
        ),
    ]
